spring.application.name=file-upload

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

spring.h2.console.enabled=true

# File size limit
spring.servlet.multipart.max-file-size=100KB
spring.servlet.multipart.max-request-size=100KB